//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TicketDetails
    {
        public int TicketID { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public Nullable<decimal> TicketCost { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<bool> TicketStatus { get; set; }
    }
}
